[WIP] Use templated index for smoke tests.
cloudfoundry-community/logsearch-for-cloudfoundry pull request #250
Opened 2017-04-25 00:50 UTC by jmcarp

Goes with https://github.com/cloudfoundry-community/logsearch-smoke-tests/pull/2. Note--will need to update submodule before merge.

2017-04-25 19:17 UTC, jmcarp commented
Updated tests submodule and changelog.

2017-04-25 19:49 UTC, Infra-Red requested changes

2017-04-25 19:49 UTC, Infra-Red commented on jobs/smoke-tests/spec
> +    default: 'logs-app-{{.Org}}-{{.Space}}-{{.Time.Format "2006-01-02"}}'
@jmcarp Default app index also need to be updated to `logs-app-{{.Org}}-{{.Space}}-{{.Time.Format \"2006.01.02\"}}`. Everything else lgtm.

2017-04-26 14:43 UTC, jmcarp commented
Updated!

2017-04-27 09:38 UTC, Infra-Red commented
@jmcarp I've applied the patch and got `ERROR: invalid character '2' after object key:value pair` error. I guess that escaping also need to be included in the index pattern.

2017-04-27 14:04 UTC, jmcarp commented
Thanks, updated to escape double quotes.

2017-04-27 14:08 UTC, Infra-Red approved these changes

2017-04-27 14:08 UTC, merged