Set required and default properties for kibana auth.
cloudfoundry-community/logsearch-for-cloudfoundry pull request #260
Opened 2017-06-08 01:47 UTC by jmcarp

At the moment, kibana auth configuration variables are passed as arbitrary hashes to `kibana.env`. As my team noticed, that means it's easy to specify an invalid configuration by forgetting required properties. There's also no good way to set default properties. This patch adds properties for the `kibana-auth-plugin` package so that we can make some properties required and set defaults for others. I'm sending a second patch to `logsearch-boshrelease` that allow the kibana control script to source arbitrary files.

I was also thinking about handling this using bosh links and exposing properties from this job to the kibana job in `logsearch-boshrelease`, but I slightly prefer this approach because it allows us to decouple the bosh property names from the environment variables that the auth plugin expects.

cc @cnelson @rogeruiz @wjwoodson

2017-06-08 12:14 UTC, rogeruiz requested changes
Looks good besides the typo. Elegant solution! 👍🏽

2017-06-08 12:14 UTC, rogeruiz commented on jobs/kibana-auth-plugin/config/config.sh.erb
> +export KIBANA_OAUTH2_CLIENT_SECRET="<%= p("kibana-auth.cloudfoundry.client_id") %>"
Looks like these properties need to be corrected and I don't see the skip SSL validation property being used here.

2017-06-08 15:54 UTC, Infra-Red requested changes
@jmcarp Could you also update deployment templates with new properties?

2017-06-09 18:54 UTC, jmcarp commented
Thanks for reviewing @Infra-Red. I updated the templates.

2017-06-12 18:28 UTC, Infra-Red approved these changes

2017-06-12 18:28 UTC, merged