Change mappings to be compatible with ES6
cloudfoundry-community/logsearch-for-cloudfoundry pull request #306
Opened 2018-11-06 12:48 UTC by hannayurkevich

Changes include:
1) Replace datatype "string" with "keyword" for not analyzed values and "text" for full-text-search values (as per https://www.elastic.co/blog/strings-are-dead-long-live-strings). Use "index":true for all values.
2) Change mappings to define properties in one type "doc" instead of multiple types (as per https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html). Note the name is chosen to correspond the name used in mappings in elasticsearch-boshrelease es6 branch ( see commit https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/1c48c2fce1eaa5e5e49aeedc48a1b8d852203261)

2018-11-06 12:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudfoundry-community/logsearch-for-cloudfoundry?pullRequest=306) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudfoundry-community/logsearch-for-cloudfoundry?pullRequest=306) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudfoundry-community/logsearch-for-cloudfoundry?pullRequest=306) it.</sub>

2018-11-10 12:16 UTC, axelaris requested changes
Could you please do two amendments, and point this PR to `es6` branch instead of `develop`.
Thanks.

2018-11-10 12:16 UTC, axelaris commented on jobs/elasticsearch-config-lfc/templates/index-mappings-app.json.erb
> +keyword_default = { "type": "string", "index": true }.to_json
It seems to be a typo. `keyword` is expected

2018-11-10 12:16 UTC, axelaris commented on jobs/elasticsearch-config-lfc/templates/index-mappings-app.json.erb
>          "@cf": {
It's a second instance of `@cf`. Probably added by mistake

2018-11-13 10:26 UTC, axelaris approved these changes

2018-11-13 11:49 UTC, hannayurkevich commented
@axelaris 

I've made requested changes. Please check.

2018-11-20 12:20 UTC, merged

2018-11-20 12:20 UTC, axelaris commented
Thank you @hannayurkevich!