Update to latest develop branch of firehose-to-syslog so it uses logg…
cloudfoundry-community/logsearch-for-cloudfoundry pull request #335
Opened 2019-10-18 05:28 UTC by Scoobed

…egrator v2 endpoints

We just downloaded the Logsearch-for-cloudfoundry 210.3.1 but we had assumed this version pointed to latest firehose-to-syslog branch so we could use loggegrator v2 endpoints

The git submodule for firehose-to-syslog -- points to this commit not the develop branch like expected.

https://github.com/cloudfoundry-community/firehose-to-syslog/tree/b88def89e19a52e9c00bc11494dfdf68244b6602  is from Oct 2018

We noticed this problem when I had cloned this project and ran a test bosh-release because it did not look to be attaching to upstream develop, like the git submodules seemed to think.

We tried this --

git submodule update --init --recursive  
This just pulled it but not the lates

git submodule foreach git pull origin develop
This was able to pull the submodule

This pull request includes that update...

2019-10-18 07:02 UTC, Infra-Red requested changes
With this change `firehose-to-syslog` submodule is now pointing to invalid commit `5b66fc`. Could you please checkout submodule to latest develop branch state https://github.com/cloudfoundry-community/firehose-to-syslog/commit/d7b57b3894bf9f67047741ccd8f7b04bf67539f6.

2019-10-18 12:55 UTC, Scoobed commented
Moved to commit id requested.  We will run a test with commit id in our environment

2019-10-20 19:06 UTC, Infra-Red approved these changes

2019-10-20 19:06 UTC, merged

2019-10-20 19:06 UTC, Infra-Red commented
@Scoobed Thanks for the contribution!